# .readthedocs.yaml
version: 2

# build:
  # image: latest
  
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    - requirements: docs/requirements.txt
